language: php

php:
  - 7.0
  - 7.1

services:
  - postgresql

install:
  - composer self-update
  - composer install --prefer-dist --no-interaction

before_script:
  - psql -c 'create database OceanProject;' -U postgres
  - phpenv rehash
  - npm install

script:
  - php artisan migrate --seed
  - vendor/bin/phpunit --coverage-text
  - vendor/bin/phpcs -p --extensions=php --standard=PSR2 --ignore=app/Http/Controllers/Auth,app/Http/Controllers/Controller.php app/Http/Controllers
  - npm run production
  - jshint resources/assets/js/*