language: php
sudo: required
dist: trusty

php:
  - 7.0
  - 7.1

env:
  global:
    - DEFAULT=1

addons:
  postgresql: "9.6"
services:
  - postgresql

matrix:
  fast_finish: true

  allow_failures:
    - php: 7.0
      env: COVERAGE=1 DEFAULT=0

  include:
    - php: 7.0
      env: PHPCS=1 DEFAULT=0
    - php: 7.0
      env: COVERAGE=1 DEFAULT=0

install:
  - composer self-update
  - composer install --prefer-dist --no-interaction

before_script:
  - psql --version
  - psql -c 'create database ocean_project;' -U postgres
  - psql -c 'create extension if not exists citext with schema public;' -U postgres
  - phpenv rehash
  - php artisan migrate --seed

script:
  - sh -c "if [ '$DEFAULT' = '1' ]; then vendor/bin/phpunit; fi"
  - sh -c "if [ '$PHPCS' = '1' ]; then vendor/bin/phpcs -p --extensions=php --standard=PSR2 ./app; fi"
  - sh -c "if [ '$COVERAGE' = '1' ]; then vendor/bin/phpunit --coverage-text; fi"
